### ISSUE TITLE
Bass Frequency Drops Out

### ISSUE THREAD

**Issue by ghost** [xcaliburinhand/DockSoundRedirector#2]
There is a big difference if I plug in my phone thru headphone Jack versus thru the USB port then to Jack. Most of the bass seems to drop out. Any fixes?

**Comment by xcaliburinhand** [comment]
What Phone, ROM, Kernel, and dock?

Thanks.

**Comment by ghost** [comment]
Samsung Captivate, Cognition, 2.6.32.9, Samsung Car Dock

Drops out my subwoofer audio and most bass.

**Comment by xcaliburinhand** [comment]
I've seen other reports of similar issues with Cog using the Cog Kernel.  I don't have insight into the Cog kernel source to see why.  Is there a chance you could try a different kernel with cognition and see if that resolves the issue?
